Repository DSC-PHCET/gdsc-android-app, pull requests merged in 2022-03, with the labels that each got.

#27 Fix #25: Implemented UpcomingEvents RecyclerView
  app/src/main/java/com/finite/gdscphcet/adapters/UpcomingEventsAdapter.kt
  app/src/main/java/com/finite/gdscphcet/model/UpcomingEventModel.kt
  app/src/main/java/com/finite/gdscphcet/ui/EventDetailActivity.kt
  app/src/main/java/com/finite/gdscphcet/ui/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Level3, GSSoC22

#28 Added TrackDetailActivity
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/finite/gdscphcet/ui/AboutFragment.kt
  app/src/main/java/com/finite/gdscphcet/ui/TrackDetailActivity.kt
  app/src/main/res/layout/activity_track_detail.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: Level2, GSSoC22

#34 added contributor badge
  README.md
Labels: documentation, good first issue, Level1, GSSoC22

#52 Share Events Function Add
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/finite/gdscphcet/ui/EventDetailActivity.kt
  app/src/main/res/layout/activity_event_detail.xml
Labels: Level2, GSSoC22

#58 issue#53 solved
  .idea/gradle.xml
  app/src/main/java/com/finite/gdscphcet/CertificateActivity.kt
  app/src/main/res/drawable-xhdpi/white_circle.xml
  app/src/main/res/layout/activity_certificate.xml
Labels: good first issue, Level2, GSSoC22
